apiVersion: batch/v1
kind: Job
metadata:
  name: job-grr-client-builder
spec:
  template:
    spec:
      serviceAccountName: osdfir-grr-sa
      initContainers:
        - name: init-kaniko-env
          image: bitnami/git
          command: ['sh', '-c', "cd /kaniko-build; git clone https://github.com/daschwanden/osdfir-infrastructure.git; cd osdfir-infrastructure; git checkout feature/grr; cp /grr/grr.server.yaml charts/osdfir-infrastructure/charts/grr/containers/grr-client/config/"]
          volumeMounts:
          - name: kaniko-volume
            mountPath: /kaniko-build
          - name: grr-server-config
            mountPath: /grr/grr.server.yaml
            subPath: server.local.yaml
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=Dockerfile.kaniko"
            - "--context=dir:///kaniko-build/osdfir-infrastructure"
            - "--context-sub-path=charts/osdfir-infrastructure/charts/grr/containers/grr-client/"
            - "--destination=europe-west1-docker.pkg.dev/osdfir-grr/containers/grr-client:v0.2"
            - "--build-arg=FLEETSPEAK_FRONTEND=10.132.0.7"
            - "--build-arg=FLEETSPEAK_FRONTEND_PORT=4443"
          volumeMounts:
          - name: grr-exe-sign-keys
            mountPath: /grr/exe/sign/keys
          - name: kaniko-volume
            mountPath: /kaniko-build
      restartPolicy: Never
      volumes:
        - name: kaniko-volume
          emptyDir:
            sizeLimit: 25Mi
        - name: grr-exe-sign-keys
          secret:
            secretName: osdfir-grr-executable-signing-keys
        - name: grr-server-config
          secret:
            secretName: osdfir-grr-server-local
            items:
            - key: server.local.yaml
              path: server.local.yaml
