{{- if .Values.fleetspeak.spanner.useSpanner }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grr-fleetspeak-spanner-components
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  database.components.textproto: |
    spanner_config: <
      project_id: "{{ .Values.fleetspeak.spanner.project }}"
      instance_name: "{{ .Values.fleetspeak.spanner.instance }}"
      database_name: "{{ .Values.fleetspeak.spanner.database }}"
      pubsub_topic: "{{ .Values.fleetspeak.spanner.topic }}"
      pubsub_sub: "{{ .Values.fleetspeak.spanner.subscription }}"
    >
{{- end }}
