apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grr-fleetspeak-mysql-components
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  database.components.textproto: |
    mysql_data_source_name: "{{ .Values.fleetspeak.mysqlDb.userName }}:{{ .Values.fleetspeak.mysqlDb.userPassword }}@tcp({{ .Values.fleetspeak.mysqlDb.address }}:{{ .Values.fleetspeak.mysqlDb.port }})/{{ .Values.fleetspeak.mysqlDb.name }}"
