apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grr-fleetspeak-admin
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    app: fleetspeak-admin
spec:
  replicas: {{ .Values.fleetspeak.admin.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fleetspeak-admin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleetspeak-admin
        prometheus: fleetspeak-admin
    spec:
      serviceAccountName: {{ .Release.Name }}-grr-sa
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nodepool
                operator: In
                values:
                - grr
      initContainers:
      {{- if .Values.fleetspeak.spanner.emulateSpanner }}
      - name: init-spanner-setup
        image: {{ .Values.initContainer.image }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          until curl -sf "http://pubsub.default.svc.cluster.local:8085/v1/projects/{{ .Values.fleetspeak.spanner.project }}/subscriptions/{{ .Values.fleetspeak.spanner.subscription }}" > /dev/null;
          do
            echo "Waiting for spanner subscription...";
            sleep 5;
          done
          echo "Spanner subscription is ready"
      {{- end }}
      - name: init-mysql-server
        image: {{ .Values.initContainer.image }}
        command: ['/bin/sh', '-c']
        args:
        - |
          until nc -z {{ .Values.fleetspeak.mysqlDb.address }} {{ .Values.fleetspeak.mysqlDb.port }};
          do
            echo "Waiting for MySQL server...";
            sleep 5;
          done
          echo "MySQL server is ready";
      - name: init-fleetspeak-admin
        image: {{ .Values.initContainer.image }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          cp /stage/fleetspeak-server/server.*.config /etc/fleetspeak-server/
          cat /stage/fleetspeak-database.config >> /etc/fleetspeak-server/server.components.config
        volumeMounts:
        - name: fleetspeak-config-volume
          mountPath: /etc/fleetspeak-server
        - name: fleetspeak-database-components
          mountPath: /stage/fleetspeak-database.config
          subPath: database.components.config
        - name: fleetspeak-admin-components
          mountPath: /stage/fleetspeak-server/server.components.config
          subPath: server.components.config
        - name: fleetspeak-services
          mountPath: /stage/fleetspeak-server/server.services.config
          subPath: server.services.config
      containers:
      - name: fleetspeak-admin
        image: {{ .Values.fleetspeak.admin.image }}
        {{- if .Values.global.useResourceRequests }}
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
        {{- end }}
        {{- if .Values.fleetspeak.spanner.emulateSpanner }}
        env:
        - name: SPANNER_EMULATOR_HOST
          value: "spanner.default.svc.cluster.local:9010"
        - name: PUBSUB_EMULATOR_HOST
          value: "pubsub.default.svc.cluster.local:8085"
        {{- end }}
        ports:
        - containerPort: {{ .Values.fleetspeak.admin.listenPort }}
          name: admin
        - containerPort: {{ .Values.fleetspeak.admin.healthCheckPort }}
          name: healthz
        - containerPort: {{ .Values.prometheus.metricsPort }}
          name: metrics
        command: ["/fleetspeak/bin/server"]
        args: ["-alsologtostderr"]
        volumeMounts:
        volumeMounts:
        - name: fleetspeak-config-volume
          mountPath: /etc/fleetspeak-server
      volumes:
      - name: fleetspeak-config-volume
        emptyDir:
          sizeLimit: 5Mi
      - name: fleetspeak-admin-components
        secret:
          secretName: {{ .Release.Name }}-grr-fleetspeak-admin-components
          items:
          - key: admin.components.textproto
            path: server.components.config
      - name: fleetspeak-services
        configMap:
          name: {{ .Release.Name }}-grr-fleetspeak-services
          items:
          - key: services.textproto
            path: server.services.config
      - name: fleetspeak-database-components
        secret:
          {{- if .Values.fleetspeak.spanner.useSpanner }}
          secretName: {{ .Release.Name }}-grr-fleetspeak-spanner-components
          {{- else }}
          secretName: {{ .Release.Name }}-grr-fleetspeak-mysql-components
          {{- end }}
          items:
          - key: database.components.textproto
            path: database.components.config
