apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fleetspeak-frontend
  {{- if .Values.grr.namespaceClient }}
  namespace: {{ .Values.grr.namespaceClient }}
  {{- end }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  {{- if .Values.fleetspeak.frontend.address }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.fleetspeak.frontend.address }}
  selector:
    app.kubernetes.io/name: fleetspeak-frontend
  {{- end }}
  ports:
  - name: fleetspeak-frontend
    protocol: TCP
    port: {{ .Values.fleetspeak.frontend.listenPort  }}
    targetPort: {{ .Values.fleetspeak.frontend.listenPort  }}
