apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grr-fleetspeak-admin-components
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  admin.components.textproto: |
    admin_config: <
      listen_address: "0.0.0.0:{{ .Values.fleetspeak.admin.listenPort }}"
    >
    notification_use_http_notifier: true
    stats_config: <
      address: "0.0.0.0:{{ .Values.prometheus.metricsPort }}"
    >
    health_check_config: <
      listen_address: "0.0.0.0:{{ .Values.fleetspeak.admin.healthCheckPort }}"
    >
