{{- $cert := genSelfSignedCert "executable-signing" nil nil 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: sec-grr-executable-signing-keys
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
    exe-sign-private-key.pem: {{ $cert.Key | b64enc }}
    exe-sign-public-key.pem: {{ $cert.Cert | b64enc }}
