{{- if .Values.global.emulateSpanner }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-spanner-setup
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: grr
    app.kubernetes.io/component: setup-spanner
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-grr-sa
      initContainers:
        - name: init-spanner-health-check
          image: {{ .Values.initContainer.image }}
          command: ["/bin/sh", "-c"]
          args:
          - |
            set -e
            until curl -sf "http://spanner:9020/v1/projects/spanner-emulator-project/instances" > /dev/null;
            do
              echo "Waiting for spanner emulator...";
              sleep 5;
            done
            echo "Spanner emulator is ready"
      containers:
        - name: cloud-sdk
          image: google/cloud-sdk:emulators
          command: ["/bin/bash", "-c"]
          args:
          - |
            set -e
            # 0) Set up the config
            gcloud config configurations create emulator
            gcloud config set auth/disable_credentials true
            gcloud config set project spanner-emulator-project --quiet
            gcloud config set api_endpoint_overrides/spanner \
              http://spanner.default.svc.cluster.local:9020/ --quiet
            # 1) Create the Spanner instance
            gcloud spanner instances create fleetspeak-instance --nodes=1 \
              --config=emulator --description="Fleetspeak Instance"
            curl -O https://raw.githubusercontent.com/google/fleetspeak/refs/heads/master/spanner-setup/fleetspeak.pb
            curl -O https://raw.githubusercontent.com/google/fleetspeak/refs/heads/master/spanner-setup/setup.sh
            # 2) Setup the Spanner Database and its Tables
            bash setup.sh
            #3) Set the environment variables
            export PUBSUB_PROJECT_ID=spanner-emulator-project
            export PUBSUB_EMULATOR_HOST=pubsub.default.svc.cluster.local:8085
            #4) Install binaries
            apt update
            apt install git -y
            apt install python3-pip -y
            apt install python3.13-venv -y
            # 5) Create venv
            python3 -m venv $HOME/.venv
            source $HOME/.venv/bin/activate
            # 6) Clone the repo
            git clone https://github.com/googleapis/python-pubsub.git
            cd python-pubsub/samples/snippets
            # 7) Install python dependencies
            pip install -r requirements.txt
            # 8) Create the PubSub Topic
            python publisher.py spanner-emulator-project create fleetspeak-top
            # 9) Create the PubSub Subscription
            python subscriber.py spanner-emulator-project create fleetspeak-top fleetspeak-sub
      restartPolicy: Never
{{- end }}
