apiVersion: batch/v1
kind: Job
metadata:
  name: job-grr-client-builder
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-grr-sa
      initContainers:
        - name: init-kaniko-env
          image: bitnami/git
          command: ["/bin/sh", "-c"]
          args:
          - |
            set -e
            cp /sign/keys/*.pem /grr/exe/sign/keys/
            if [ -e /sign/keys/exe-sign.crt ]
            then
              echo "Extracting public key from certificate..."
              openssl x509 -in /sign/keys/exe-sign.crt -pubkey -noout > /grr/exe/sign/keys/exe-sign-public-key.pem
            fi
            cd /kaniko-build; 
            git clone https://github.com/daschwanden/osdfir-infrastructure.git
            cd osdfir-infrastructure
            git checkout feature/grr
            cp /grr/grr.server.yaml charts/osdfir-infrastructure/charts/grr/containers/grr-client/config/
          volumeMounts:
          - name: grr-exe-sign-keys-volume
            mountPath: /grr/exe/sign/keys
          - name: grr-exe-sign-keys-secret
            mountPath: /sign/keys
          - name: kaniko-volume
            mountPath: /kaniko-build
          - name: grr-server-config
            mountPath: /grr/grr.server.yaml
            subPath: server.local.yaml
      containers:
        - name: kaniko
          image: gcr.io/kaniko-project/executor:latest
          args:
            - "--dockerfile=Dockerfile.kaniko"
            - "--context=dir:///kaniko-build/osdfir-infrastructure"
            - "--context-sub-path=charts/osdfir-infrastructure/charts/grr/containers/grr-client/"
            - "--destination={{ .Values.grr.daemon.image }}"
            - "--build-arg=FLEETSPEAK_FRONTEND={{ .Values.fleetspeak.frontend.address }}"
            - "--build-arg=FLEETSPEAK_FRONTEND_PORT={{ .Values.fleetspeak.frontend.listenPort }}"
          volumeMounts:
          - name: grr-exe-sign-keys-volume
            mountPath: /grr/exe/sign/keys
          - name: kaniko-volume
            mountPath: /kaniko-build
      restartPolicy: Never
      volumes:
        - name: kaniko-volume
          emptyDir:
            sizeLimit: 25Mi
        - name: grr-exe-sign-keys-volume
          emptyDir:
            sizeLimit: 5Mi
        - name: grr-exe-sign-keys-secret
          secret:
            secretName: {{ .Release.Name }}-grr-executable-signing-keys
        - name: grr-server-config
          secret:
            secretName: {{ .Release.Name }}-grr-server-local
            items:
            - key: server.local.yaml
              path: server.local.yaml
