apiVersion: v1
kind: ConfigMap
metadata:
  name: cfm-fleetspeak-services
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
data:
  services.textproto: |
    services {
      name: "GRR"
      factory: "GRPC"
      config {
        [type.googleapis.com/fleetspeak.grpcservice.Config] {
          target: "svc-grr-frontend:{{ .Values.grr.frontend.listenPort }}"
          insecure: true
        }
      }
    }
    broadcast_poll_time {
      seconds: 1
    }
