apiVersion: v1
kind: ConfigMap
metadata:
  name: cfm-fleetspeak-services
  namespace: grr
data:
  services.textproto: |
    services {
      name: "GRR"
      factory: "GRPC"
      config {
        [type.googleapis.com/fleetspeak.grpcservice.Config] {
          target: "svc-grr-frontend:{{ .Values.grrFrontendListenPort }}"
          insecure: true
        }
      }
    }
    broadcast_poll_time {
      seconds: 1
    }
