apiVersion: v1
kind: Secret
metadata:
  name: sec-fleetspeak-admin-components
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
stringData:
  admin.components.textproto: |
    {{- if .Values.fleetspeak.spanner.database }}
    spanner_config: {
      project_id: "{{ .Values.fleetspeak.spanner.project }}"
      instance_name: "{{ .Values.fleetspeak.spanner.instance }}"
      database_name: "{{ .Values.fleetspeak.spanner.database }}"
      pubsub_topic: "{{ .Values.fleetspeak.spanner.topic }}"
      pubsub_sub: "{{ .Values.fleetspeak.spanner.subscription }}"
    }
    {{- else }}
    mysql_data_source_name: "{{ .Values.fleetspeak.mysqlDb.userName }}:{{ .Values.fleetspeak.mysqlDb.userPassword }}@tcp({{ .Values.fleetspeak.mysqlDb.address }}:{{ .Values.fleetspeak.mysqlDb.port }})/{{ .Values.fleetspeak.mysqlDb.name }}"
    {{- end }}
    admin_config: <
      listen_address: "0.0.0.0:{{ .Values.fleetspeak.admin.listenPort }}"
    >
    notification_use_http_notifier: true
    stats_config: <
      address: "0.0.0.0:{{ .Values.prometheus.metricsPort }}"
    >
