{{- $cert := genSelfSignedCert .Values.grr.subjectCommonName nil nil 3650 }}
apiVersion: v1
kind: Secret
metadata:
  name: sec-grr-frontend-cert
  {{- if .Values.grr.namespace }}
  namespace: {{ .Values.grr.namespace }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Values.grr.generateCert }}
  grr-frontend.crt: {{ b64enc $cert.Cert }}
  grr-frontend.key: {{ b64enc $cert.Key }}
{{- else }}
  grr-frontend.crt: {{ default (.Files.Get "certs/grr-frontend.crt") .Values.grr.frontend.cert | b64enc }}
  grr-frontend.key: {{ default (.Files.Get "certs/grr-frontend.key") .Values.grr.frontend.cert | b64enc }}
{{- end }}
