apiVersion: v1
kind: Secret
metadata:
  name: sec-fleetspeak-admin-components
  namespace: grr
stringData:
  admin.components.textproto: |
    mysql_data_source_name: "{{ .Values.fleetspeakMysqlDbUserName }}:{{ .Values.fleetspeakMysqlDbUserPassword }}@tcp({{ .Values.fleetspeakMysqlDbAddress }}:{{ .Values.fleetspeakMysqlDbPort }})/{{ .Values.fleetspeakMysqlDbName }}"
    admin_config: <
      listen_address: "0.0.0.0:{{ .Values.fleetspeakAdminListenPort }}"
    >
    notification_use_http_notifier: true
    stats_config: <
      address: "0.0.0.0:{{ .Values.prometheusMetricsPort }}"
    >
