apiVersion: v1
kind: Service
metadata:
  name: svc-fleetspeak-frontend
spec:
  selector:
    app.kubernetes.io/name: fleetspeak-frontend
  ports:
    - protocol: TCP
      name: frontend
      port: {{ .Values.fleetspeakFrontendListenPort  }}
      targetPort: {{ .Values.fleetspeakFrontendListenPort }}
---
kind: Service
apiVersion: v1
metadata:
  name: fleetspeak-frontend
  namespace: grr
spec:
  type: ExternalName
  externalName: svc-fleetspeak-frontend.default.svc.cluster.local
  ports:
  - port: {{ .Values.fleetspeakFrontendListenPort  }}
