apiVersion: v1
kind: Service
metadata:
  name: svc-fleetspeak-frontend
  namespace: grr
  {{- if .Values.fleetspeak.frontend.neg }}
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.fleetspeak.frontend.listenPort }}":{"name": "k8s-fleetspeak-frontend-neg"}}}'
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: fleetspeak-frontend
  ports:
    - protocol: TCP
      name: frontend
      port: {{ .Values.fleetspeak.frontend.listenPort  }}
      targetPort: {{ .Values.fleetspeak.frontend.listenPort }}
---
kind: Service
apiVersion: v1
metadata:
  name: fleetspeak-frontend
  namespace: grr-client
spec:
  type: ExternalName
  externalName: svc-fleetspeak-frontend.grr.svc.cluster.local
  ports:
  - port: {{ .Values.fleetspeak.frontend.listenPort  }}
