apiVersion: v1
kind: Service
metadata:
  name: svc-fleetspeak-admin
spec:
  selector:
    app.kubernetes.io/name: fleetspeak-admin
  ports:
    - protocol: TCP
      name: admin
      port: {{ .Values.fleetspeakAdminListenPort }}
      targetPort: {{ .Values.fleetspeakAdminListenPort }}
