apiVersion: v1
kind: Service
metadata:
  name: svc-fleetspeak-admin
  namespace: grr
spec:
  selector:
    app.kubernetes.io/name: fleetspeak-admin
  ports:
    - protocol: TCP
      name: admin
      port: {{ .Values.fleetspeak.admin.listenPort }}
      targetPort: {{ .Values.fleetspeak.admin.listenPort }}
