apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-fleetspeak-frontend
  labels:
    app: fleetspeak-frontend
spec:
  replicas: {{ .Values.fleetspeakFrontendReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fleetspeak-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fleetspeak-frontend
        prometheus: enabled
    spec:
      initContainers:
      - name: init-fleetspeak-frontend
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: busybox:1.36
        command: ['sh', '-c', "cp /stage/fleetspeak-server/server.*.config /etc/fleetspeak-server/; sed -i \"s/FLEETSPEAK_FRONTEND_IP/$POD_IP/g\" /etc/fleetspeak-server/server.components.config"]
        volumeMounts:
        - name: fleetspeak-config-volume
          mountPath: /etc/fleetspeak-server
        - name: fleetspeak-frontend-components
          mountPath: /stage/fleetspeak-server/server.components.config
          subPath: server.components.config
        - name: fleetspeak-services
          mountPath: /stage/fleetspeak-server/server.services.config
          subPath: server.services.config
      containers:
      - name: fleetspeak-frontend
        image: {{ .Values.fleetspeakFrontendImage }}
        ports:
        - containerPort: {{ .Values.fleetspeakFrontendListenPort }}
          name: frontend
        - containerPort: {{ .Values.fleetspeakFrontendHealthCheckPort }}
          name: healthz
        - containerPort: {{ .Values.fleetspeakFrontendNotificationPort }}
          name: notification
        - containerPort: {{ .Values.prometheusMetricsPort }}
          name: metrics
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.fleetspeakFrontendHealthCheckPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        command: ["/fleetspeak/bin/server"]
        args: ["-alsologtostderr"]
        volumeMounts:
        - name: fleetspeak-config-volume
          mountPath: /etc/fleetspeak-server
      volumes:
      - name: fleetspeak-config-volume
        emptyDir:
          sizeLimit: 5Mi
      - name: fleetspeak-frontend-components
        secret:
          secretName: sec-fleetspeak-frontend-components
          items:
          - key: frontend.components.textproto
            path: server.components.config
      - name: fleetspeak-services
        configMap:
          name: cfm-fleetspeak-services
          items:
          - key: services.textproto
            path: server.services.config
