apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: openrelik
  labels:
    type: local
    app: openrelik
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/openrelik/data
